[package]
name = "surreal-repo"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
surrealdb = "2.1.4"
tokio = { version = "1.42.0", features = ["macros","rt-multi-thread"] }
